#!/usr/bin/env python3
"""Agent R: build sources.json + sources.bib by merging all peer _sources_*.jsonl
files, deduping by URL, and mapping each URL to a benchmark via the validation CSV."""
import csv
import glob
import html
import json
import os
import re

ROOT = os.path.dirname(os.path.abspath(__file__))

# 1) Map URL -> benchmark from Agent A's validation table + Agent D matrix.
url2bench = {}


def add_urls(cell, bench):
    if not cell:
        return
    for u in re.split(r"[;\s]+", cell.strip()):
        u = u.strip()
        if u.startswith("http"):
            # strip trailing parenthetical notes like "(404 ...)"
            u = u.split(" ")[0].rstrip(".,;")
            url2bench.setdefault(u, bench)


for fname in ("01_benchmark_validation_table.csv", "04_trace_feasibility_matrix.csv"):
    p = os.path.join(ROOT, fname)
    if not os.path.exists(p):
        continue
    with open(p, newline="") as f:
        for row in csv.DictReader(f):
            b = row.get("benchmark_name", "").strip()
            for col in ("github_url", "paper_url", "dataset_url", "source_urls"):
                add_urls(row.get(col, ""), b)

# 2) Merge all peer source sidecars (dedupe by URL; keep first good label).
records = {}  # url -> {label, agents:set}
for sf in sorted(glob.glob(os.path.join(ROOT, "_sources_*.jsonl"))):
    with open(sf) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                d = json.loads(line)
            except json.JSONDecodeError:
                continue
            url = (d.get("url") or "").strip()
            if not url.startswith("http"):
                continue
            url = url.split(" ")[0].rstrip(".,;")
            label = (d.get("label") or "").strip()
            agent = d.get("agent") or os.path.basename(sf).split("_")[2].split(".")[0]
            if url not in records:
                records[url] = {"label": label, "agents": set()}
            elif label and len(label) > len(records[url]["label"]):
                records[url]["label"] = label
            if agent:
                records[url]["agents"].add(agent)

# 3) Emit sources.json
out = []
for i, url in enumerate(sorted(records), 1):
    bench = url2bench.get(url, "")
    if not bench:
        # heuristic fallback for arxiv/other not in CSV cells
        bench = ""
    out.append(
        {
            "id": f"s{i:03d}",
            "label": records[url]["label"],
            "url": url,
            "benchmark": bench,
            "cited_by": "".join(sorted(records[url]["agents"])),
        }
    )
with open(os.path.join(ROOT, "sources.json"), "w") as f:
    json.dump(out, f, indent=2, ensure_ascii=False)


# 4) Emit sources.bib (best-effort, keyed by benchmark, one entry per arXiv/paper URL).
def bibkey(s):
    return re.sub(r"[^A-Za-z0-9]", "", s) or "src"


seen_keys = {}
bibs = []
# prefer paper_url rows from the validation CSV for clean citations
papers = {}  # bench -> paper_url
p = os.path.join(ROOT, "01_benchmark_validation_table.csv")
with open(p, newline="") as f:
    for row in csv.DictReader(f):
        b = row.get("benchmark_name", "").strip()
        pu = (row.get("paper_url", "") or "").strip().split(" ")[0]
        if b and pu.startswith("http"):
            papers[b] = pu

for bench, pu in sorted(papers.items()):
    key = bibkey(bench)
    n = seen_keys.get(key, 0)
    seen_keys[key] = n + 1
    if n:
        key = f"{key}{n}"
    m = re.search(r"arxiv\.org/abs/([0-9.]+)", pu)
    if m:
        bibs.append(
            f"@misc{{{key},\n  title  = {{{bench}}},\n  note   = {{Benchmark/dataset for HHRouting-Bench}},\n"
            f"  eprint = {{{m.group(1)}}},\n  archivePrefix = {{arXiv}},\n  howpublished = {{\\url{{{pu}}}}}\n}}"
        )
    else:
        bibs.append(
            f"@misc{{{key},\n  title  = {{{bench}}},\n  note   = {{Benchmark/dataset for HHRouting-Bench}},\n"
            f"  howpublished = {{\\url{{{pu}}}}}\n}}"
        )

with open(os.path.join(ROOT, "sources.bib"), "w") as f:
    f.write(
        "% HHRouting-Bench source bibliography (best-effort, keyed by benchmark).\n"
    )
    f.write(
        "% Auto-generated by Agent R from peer paper_url fields. Verify before publication.\n\n"
    )
    f.write("\n\n".join(bibs) + "\n")

print(f"sources.json: {len(out)} unique URLs")
print(f"sources.bib : {len(bibs)} BibTeX entries")
print(f'URLs mapped to a benchmark: {sum(1 for r in out if r["benchmark"])}/{len(out)}')
